[package]
name = "nbody"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = { version = "*", features = ["rand", "fast-math"] }
rand = "*"
eframe = "*"
rayon = "*"
parking_lot = "*"
wgpu = "*"
pollster = "*"
bytemuck = "*"
